### ISSUE TITLE
Customize trader's assort prices

### ISSUE THREAD

**Issue by ckhawks** [acidphantasm/acidphantasm-scorpion#3]
Hi -- directed to post this request here :)

I'd love a way to customize a multiplier for the traderAssort item prices, so that I can increase/decrease the overall price of all of their items across the board, as personally I feel like they are too cheap for my taste.

Appreciate it!

**Comment by acidphantasm** [comment]
This should be resolved in the upcoming release

5ea2de64b6631cfbf051f8d7abc442e0def8d176
